ARG LLMD_VERSION=0.5.0

FROM ghcr.io/llm-d/llm-d-cuda:v$LLMD_VERSION

LABEL org.opencontainers.image.source=https://github.com/almogtavor/vllm-container-builder
LABEL org.opencontainers.image.description="Segmented Spans support for llm-d's vLLM (omerpaz95)"
LABEL org.opencontainers.image.licenses="Apache-2.0"

ARG LLMD_VERSION=0.5.0

COPY docker/vllm/llm-d/patches/$LLMD_VERSION/ /tmp/patches
USER root
RUN cd /opt/vllm-source \
    && ls /tmp/patches \
    && for patchfile in /tmp/patches/*.patch.gz; do git apply <(gunzip -c $patchfile); done
USER vllm
